FRW-5917 Integrated Zed as Gateway.
spryker-shop/b2c-demo-marketplace pull request #174
Opened 2023-09-14 16:37 UTC by olhalivitchuk

#### Overview

- Ticket: https://spryker.atlassian.net/browse/FRW-5917

2023-09-18 12:13 UTC, dimitriyTsemma approved these changes

2023-09-19 12:20 UTC, asmarovydlo requested changes

2023-09-19 12:20 UTC, asmarovydlo commented on src/Pyz/Zed/EventDispatcher/EventDispatcherDependencyProvider.php
>      protected function getEventDispatcherPlugins(): array
Why changes for src/Pyz/Zed/Console/ConsoleDependencyProvider.php is missing?

2023-09-19 12:25 UTC, asmarovydlo approved these changes

2023-09-25 08:00 UTC, merged