[WIP] CC-29651 Click&Collect integration
spryker-shop/b2c-demo-marketplace pull request #195
Opened 2023-10-17 17:08 UTC by romanhavrylko

#### Overview

- Ticket: https://spryker.atlassian.net/browse/CC-29651

2023-10-18 15:07 UTC, abitskil reviewed
Looks good as the early integration, requires an additional round of review when the feature is stabilized. 

Notes:
* Data import files have to be substituted by demo shop specific ones.

2023-10-31 19:40 UTC, FRITS-Kh requested changes

2023-10-31 19:40 UTC, FRITS-Kh commented on src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/main-popup.scss
> +        }
Please use a modifier in the `icon` instead.

2023-10-31 19:40 UTC, FRITS-Kh commented on src/Pyz/Yves/ShopUi/Theme/default/components/molecules/search-form/search-form.twig
> +                    autocomplete="off"
```suggestion
                    name="q"
                    class="suggest-search__input suggest-search__input--expand {{ config.jsName }}__input--{{ attributes['data-search-id'] }}"
                    placeholder="{{ 'global.search' | trans }}"
                    value="{{ data.searchValue }}"
                    autocomplete="off"
                    autofocus
```

2023-11-01 11:03 UTC, danilmoro3 commented on src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
> +                                            class: embed.addressSelectClassName ~ ' ' ~ embed.deliveryContainerClassName ~ ' ' ~ embed.shipmentTypeHiddenClassName ~ ' ' ~ embed.jsName ~ '__trigger--'
They are duplicated in core as well 
Removed duplicate in demoshop

2023-11-01 11:04 UTC, danilmoro3 commented on src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
>                                  hasStatus: false,
Yes, like product options or attributes

2023-11-01 12:18 UTC, danilmoro3 commented on src/Pyz/Yves/ShopUi/Theme/default/components/organisms/side-drawer/side-drawer.ts
> +    toggle(isShownFromOutside?: boolean): void {
Copy-past from core 
Made it protected

2023-11-01 15:56 UTC, danilmoro3 commented on src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
> +                    class: shippingClassName ~ ' ' ~ shippingValidationContainerClassName ~ ' ' ~ (isAddressSelected ? hiddenClassName),
Moved variables out of condition

2023-11-01 15:56 UTC, danilmoro3 commented on src/Pyz/Yves/ShopUi/Theme/default/components/molecules/main-popup/main-popup.scss
> +    padding: rem(20);
height and width works as expected

2023-11-01 19:52 UTC, FRITS-Kh requested changes

2023-11-01 19:52 UTC, FRITS-Kh commented on src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
> +            {% set shippingAddressValue = shippingAddress.vars.value %}
The `shippingAddress` can be undefined and it leads to an error in the `shippingAddressValue`.
Please check the workflow with a customer without saved addresses.

2023-11-01 19:52 UTC, FRITS-Kh commented on src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
> +                    {% set billingAddressValue = data.form.id_customer_address.vars.value %}
The same, can't get a value from undefined.

2023-11-01 20:19 UTC, FRITS-Kh approved these changes

2023-11-03 11:37 UTC, abitskil approved these changes

2023-11-03 12:24 UTC, merged