CC-31600: Fixed warehouse user assignment validation
spryker-shop/b2c-demo-marketplace pull request #233
Opened 2023-11-10 11:54 UTC by michbeck

#### Overview

- Ticket: https://spryker.atlassian.net/browse/CC-31829

###### Optional

- Core PR: https://github.com/spryker/spryker/pull/10580

2023-11-10 12:03 UTC, romanhavrylko approved these changes

2023-11-10 12:51 UTC, DmitryLymarenko commented on composer.json
> -        "spryker/warehouse-users-backend-api": "^1.0.1",
why was it removed?

2023-11-10 13:04 UTC, michbeck commented on composer.json
> -        "spryker/warehouse-users-backend-api": "^1.0.1",
Fixed

2023-11-10 13:34 UTC, DmitryLymarenko approved these changes

2023-11-10 14:47 UTC, DmitryLymarenko requested changes

2023-11-10 14:47 UTC, DmitryLymarenko commented on composer.json
> +        "spryker/warehouse-users-backend-api": "1.1.0",
```suggestion
        "spryker/warehouse-users-backend-api": "^1.1.0",
```

please use the instructions from delivery channel in slack

2023-11-13 09:14 UTC, DmitryLymarenko approved these changes

2023-11-17 08:54 UTC, DmitryLymarenko approved these changes

2023-11-17 08:54 UTC, merged